export const characterOrder = {
    "Trixion": ["Beatrice"],
    "Trua, the Forgotten Land": ["Kharmine"],
    "Rethramis": ["Armen", "Neria"],
    "Yudia": [],
    "West Luterra": ["Luterra", "Thirain"],
    "East Luterra": ["Executor Solas", "Valtan", "Kakul Saydon", "Blackfang"],
    "Tortoyk": [],
    "Anikka": ["Luen", "Sien", "Vykas", "Wei"],
    "Arthetine": ["Bastian", "Sasha"],
    "North Vern": ["Ealyn", "Vairgrys"],
    "Shushire": ["Akkan"],
    "Rohendel": ["Azena", "Inanna", "Brelshaza"],
    "Yorn": ["Galatur", "Balthorr"],
    "Feiton": ["Jederico", "Zaika"],
    "Whispering Islet": ["Nineveh"],
    "Illusion Bamboo Island": ["Shandi", "Zinnervale"],
    "Punika": ["Liru", "Nia", "Shana", "Jahara"],
    "Isteri": ["Kadan"],
    "South Vern": ["Avele", "Thaemine", "Thar"],
    "Rowen": [],
    "Elgacia": ["Lauriel"],
    "Pleccia": ["Gustaven"],
    "Voldis": ["Varkan", "Mariu", "Zeherade"],
    "South Kurzan": ["Ren", "Behemoth", "Echidna"],
    "North Kurzan": ["Aegir", "Kazeros"],
    "South Rimeria": [],
    "North Rimeria": []
}